stages:
  - deploy

deploy:
  stage: deploy
  only:
    - master
  when: manual  # запуск вручную
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

    # Синхронизация файлов
    - rsync -avz --exclude '.git' . $USER@$SERVER_IP:$REMOTE_DIR

    # Команды на сервере
    - ssh $USER@$SERVER_IP << 'EOF'
      set -e
      cd $REMOTE_DIR
      
      echo "🔄 Перезапуск docker-контейнеров..."
      docker compose down
      docker compose up -d --build
      
      echo "🔍 Проверка изменений composer.json и миграций..."
      CHANGED=$(git diff --name-only HEAD~1 HEAD || true)
      
      if echo "$CHANGED" | grep -qE 'composer\.json|composer\.lock'; then
      echo "📦 Выполняем composer install..."
      docker compose exec -T php composer install --no-interaction --prefer-dist --optimize-autoloader
      else
      echo "✅ composer.json не изменялся — пропускаем composer install"
      fi
      
      if echo "$CHANGED" | grep -qE '^migrations/'; then
      echo "🧱 Выполняем doctrine:migrations:migrate..."
      docker compose exec -T php php bin/console doctrine:migrations:migrate --no-interaction
      else
      echo "✅ Миграции не изменялись — пропускаем"
      fi
      EOF
