version: '3.3'

services:
  api:
    container_name: api
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./api:/var/www/test
    depends_on:
      - mysql
    networks:
      - test
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8081:8081'
    volumes:
      - ./api:/var/www/test
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test
    depends_on:
      - api
  mysql:
    container_name: test_mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'test'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3305:3306'
    networks:
      - test

networks:
  test:
    name: test


volumes:
  mysql:
